name: 'AngularWay'
version: 0.0.1
description: Slides for speech "The Angular Way. Best practices in Angular JS".
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: '>=1.0.0 <1.2.0'
  browser: '>=0.10.0 <0.11.0'
  dacsslide: 'any'
  csslib_transform: '>=0.0.1 <0.1.0'
  pretty_samples: 'any'
  http_server: ">=0.9.5+1 <0.10.0"
  redstone: ">=0.5.18 <0.6.0"
transformers:
- angular
- dacsslide
- csslib_transform